services:
  brittle-api:
    build:
      context: .
      target: brittle-api
    command:
      - serve
      - --api-failure-rate=0.5
      - --api-silent-failure-rate=0.3
      - --api-min-latency=1
      - --api-max-latency=3
      - :8000
    ports:
      - 8000:8000

  bruno:
    build: github.com/davidkarlsen/bruno-image:main
    # set working dir to the directory with the test collection
    working_dir: /tests
    volumes:
      # mount test collection into the container
      - type: bind
        source: ./bruno
        target: /tests
    profiles:
      # set a profile to prevent this from being started by default
      - bruno

  # Note: The broker doesn't start as a service here, it just runs the broker
  # executable once. This is rather a placeholder than an actual service.
  mongodb-broker:
    build:
      context: .
      target: broker
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - EVENTSTORE_DRIVER=mongodb
      - EVENTSTORE_DB_HOST=mongodb
    profiles:
      - mongodb-storage

  mongodb:
    image: mongo:4.4
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.help()"]
      interval: 10s
      timeout: 2s
      retries: 1
    ports:
      - 27017/tcp
    volumes:
      - type: bind
        source: ./docker-compose.d/setup-mongodb-event-store.sh
        target: /docker-entrypoint-initdb.d/setup-event-store.sh
      - type: volume
        source: mongodb-data
        target: /data/db
    profiles:
      - mongodb-storage
    labels:
      # Note: For Traefik, the router must have at least one rule, therefore
      # the dummy catch-all `HostSNI()` rule.
      - traefik.enable=true
      - traefik.tcp.routers.mongodb.rule=HostSNI(`*`)
      - traefik.tcp.routers.mongodb.entrypoints=mongodb

  mongodb-api:
    build: .
    depends_on:
      mongodb:
        condition: service_healthy
    command:
      - serve-rest-api
    environment:
      - EVENTSTORE_DRIVER=mongodb
      - EVENTSTORE_DB_HOST=mongodb
    ports:
      - 80
    profiles:
      - mongodb-storage
    labels:
      - traefik.enable=true
      - traefik.http.routers.mongodb-broker.entrypoints=web
      - traefik.http.routers.mongodb-broker.rule=Host(`api.docker.localhost`)
      - traefik.http.services.mongodb-broker.loadbalancer.server.port=80

  mongodb-processor:
    build:
      context: .
      target: broker
    depends_on:
      mongodb:
        condition: service_healthy
    command:
      - process
      - --api-url=http://brittle-api:8000
    environment:
      - EVENTSTORE_DRIVER=mongodb
      - EVENTSTORE_DB_HOST=mongodb
    profiles:
      - mongodb-storage

  mongodb-watcher:
    build:
      context: .
      target: broker
    depends_on:
      mongodb:
        condition: service_healthy
    command:
      - watch-requests
    environment:
      - EVENTSTORE_DRIVER=mongodb
      - EVENTSTORE_DB_HOST=mongodb
    profiles:
      - mongodb-storage

  # Note: The broker doesn't start as a service here, it just runs the broker
  # executable once. This is rather a placeholder than an actual service.
  postgresql-broker:
    build:
      context: .
      target: broker
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      - EVENTSTORE_DRIVER=postgresql
      - EVENTSTORE_DB_HOST=postgresql
    profiles:
      - postgresql-storage

  postgresql:
    image: postgres:13.8
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "db_prod"]
      interval: 10s
      timeout: 2s
      retries: 1
    ports:
      - 5432/tcp
    volumes:
      - type: bind
        source: ./docker-compose.d/setup-postgresql-event-store.sh
        target: /docker-entrypoint-initdb.d/setup-event-store.sh
      - type: volume
        source: postgresql-data
        target: /var/lib/postgresql/data
    profiles:
      - postgresql-storage
    labels:
      # Note: For Traefik, the router must have at least one rule, therefore
      # the dummy catch-all `HostSNI()` rule.
      - traefik.enable=true
      - traefik.tcp.routers.postgresql.rule=HostSNI(`*`)
      - traefik.tcp.routers.postgresql.entrypoints=postgresql

  postgresql-api:
    build: .
    depends_on:
      postgresql:
        condition: service_healthy
    command:
      - serve-rest-api
    environment:
      - EVENTSTORE_DRIVER=postgresql
      - EVENTSTORE_DB_HOST=postgresql
    ports:
      - 80
    profiles:
      - postgresql-storage
    labels:
      - traefik.enable=true
      - traefik.http.routers.postgresql-broker.entrypoints=web
      - traefik.http.routers.postgresql-broker.rule=Host(`api.docker.localhost`)
      - traefik.http.services.postgresql-broker.loadbalancer.server.port=80

  postgresql-processor:
    build:
      context: .
      target: broker
    depends_on:
      postgresql:
        condition: service_healthy
    command:
      - process
      - --api-url=http://brittle-api:8000
    environment:
      - EVENTSTORE_DRIVER=postgresql
      - EVENTSTORE_DB_HOST=postgresql
    profiles:
      - postgresql-storage

  postgresql-watcher:
    build:
      context: .
      target: broker
    depends_on:
      postgresql:
        condition: service_healthy
    command:
      - watch-requests
    environment:
      - EVENTSTORE_DRIVER=postgresql
      - EVENTSTORE_DB_HOST=postgresql
    profiles:
      - postgresql-storage

  traefik:
    image: traefik:2.10
    command:
      # turn off data exfiltration
      - "--global.checknewversion=false"
      - "--global.sendanonymoususage=false"
      # web UI / dashboard
      - "--api.insecure=true"
      # configuration
      - "--log.level=DEBUG"
      - "--providers.docker=true"
      # define MongoDB entrypoint
      - --entrypoints.mongodb.address=:27017
      # define PostgreSQL entrypoint
      - --entrypoints.postgresql.address=:5432
      # define web entrypoint
      - --entrypoints.web.address=:80
    ports:
      - 80:80
      # web UI at http://traefik.docker.localhost:8080
      # (enabled by --api.insecure=true)
      - 8080:8080
      # expose MongoDB port
      - 27017:27017/tcp
      # expose PostgreSQL port
      - 5432:5432/tcp
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock

volumes:
  mongodb-data:
  postgresql-data:
